# Generated by Django 3.2.4 on 2021-11-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='İnstagramModel',
        ),
    ]
