# Generated by Django 3.2.6 on 2021-09-20 15:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='başlık en ')),
                ('title_ar', models.CharField(blank=True, max_length=500, verbose_name='başlık ar ')),
                ('title_fa', models.CharField(blank=True, max_length=500, verbose_name='başlık fa ')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, verbose_name='uzantı')),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='öne çıkarma')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='oluşturulma tarihi')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='ana resim "1920-1100"')),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik')),
                ('intro_ar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik ar')),
                ('intro_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik fa')),
                ('read_time', models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='okuma süresi')),
                ('anahaber', models.BooleanField(default=False, verbose_name='anasayfada göster')),
            ],
            options={
                'verbose_name': 'blog yazısı',
                'verbose_name_plural': 'blog Yazıları',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='başlık en ')),
                ('title_ar', models.CharField(blank=True, max_length=500, verbose_name='başlık ar ')),
                ('title_fa', models.CharField(blank=True, max_length=500, verbose_name='başlık fa ')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, verbose_name='uzantı')),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='öne çıkarma')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='oluşturulma tarihi')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='ana resim "1920-1100"')),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik')),
                ('intro_ar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik ar')),
                ('intro_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik fa')),
                ('read_time', models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='okuma süresi')),
                ('anahaber', models.BooleanField(default=False, verbose_name='anasayfada göster')),
            ],
            options={
                'verbose_name': 'Haber yazısı',
                'verbose_name_plural': 'Haber Yazıları',
                'ordering': ['title'],
            },
        ),
    ]
