# Generated by Django 3.1 on 2021-09-27 12:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0002_auto_20210921_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='intro_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik da'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_da',
            field=models.CharField(blank=True, max_length=500, verbose_name='başlık da '),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='intro_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik da'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_da',
            field=models.CharField(blank=True, max_length=500, verbose_name='başlık da '),
        ),
    ]
