# Generated by Django 3.2.4 on 2021-10-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0003_auto_20210927_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsModel',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
