# Generated by Django 3.2.4 on 2021-10-02 23:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0004_auto_20211003_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='anahaber',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='intro_ar',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='intro_da',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='intro_fa',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_da',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_fa',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(blank=True, max_length=500, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image_tree',
            field=models.FileField(null=True, upload_to='', verbose_name='gift-image "511x475"'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image_two',
            field=models.FileField(null=True, upload_to='', verbose_name='gift-image "356x475"'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='more',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='ek içerikler'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='başlık'),
        ),
    ]
