# Generated by Django 3.1 on 2021-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0007_auto_20211007_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='bg_color_code',
            field=models.CharField(blank=True, max_length=400, verbose_name='background renk kodu'),
        ),
    ]
