# Generated by Django 3.2.4 on 2021-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0009_auto_20211027_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='bg_color_code',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image_tree',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='more',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='read_time',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
