# Generated by Django 3.2.4 on 2021-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0010_auto_20211115_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='ana resim "603-350"'),
        ),
    ]
