# Generated by Django 3.2.4 on 2021-07-23 14:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='Başlık')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='Başlık_en')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='uzantı')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='fiyat')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='eski fiyat')),
                ('mainimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim "360X380"')),
                ('decription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Açıklama')),
                ('decription_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Açıklama_en')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'ürünler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModelGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('image', models.FileField(upload_to='products-image/', verbose_name='480x288')),
                ('drinks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductModelGaleri', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'galeri ',
                'verbose_name_plural': 'galeriler',
                'ordering': ['created_date'],
            },
        ),
    ]
