# Generated by Django 3.2.4 on 2021-08-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Rating'),
        ),
    ]
