# Generated by Django 3.2.4 on 2021-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210807_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='link',
            field=models.CharField(blank=True, max_length=40, verbose_name='satın alma linki'),
        ),
    ]
