# Generated by Django 3.2.4 on 2021-11-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productmodel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='decription_en',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='title_en',
        ),
    ]
