# Generated by Django 3.2.4 on 2021-11-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211111_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='proj_type',
            field=models.CharField(choices=[('tek katlı', 'Tek Katlı'), ('çift katlı', 'Çift Katlı')], default='tek katlı', max_length=50),
        ),
    ]
