# Generated by Django 3.2.4 on 2021-11-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211114_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='proj_sub_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='proje türü'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='proj_type',
            field=models.CharField(choices=[('tek katlı', 'Tek Katlı'), ('çift katlı', 'Çift Katlı')], default='tek katlı', max_length=50),
        ),
    ]
