# Generated by Django 3.2.4 on 2021-11-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211114_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='proj_type',
            field=models.CharField(choices=[('tek katlı', 'Tek Katlı'), ('çift katlı', 'Çift Katlı')], default='tek katlı', max_length=50, verbose_name='kat sayısı'),
        ),
    ]
