# Generated by Django 3.2.4 on 2021-11-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productmodelgaleri_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelgaleri',
            name='image',
            field=models.ImageField(upload_to='products-image/', verbose_name='583x430'),
        ),
    ]
