# Generated by Django 3.2.4 on 2022-07-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productmodelgaleri_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['id'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
    ]
