# Generated by Django 3.2.4 on 2022-07-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='included',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='not_included',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='proj_code',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='proj_sub_type',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='project_detail',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='project_doc',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='rating',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='proj_type',
            field=models.CharField(choices=[('dijital baskı', 'Dijital Baskı'), ('display ürünler', 'Display Ürünler'), ('tabela sistemleri', 'Tabela Sistemleri'), ('promosyon ürünleri', 'Promosyon Ürünleri'), ('matbaa hizmetleri', 'Matbaa Hizmetleri'), ('ankara web tasarımı', 'Ankara Web Tasarımı')], default='dijital baskı', max_length=50, verbose_name='Proje ismi'),
        ),
    ]
