# Generated by Django 3.2.4 on 2022-07-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0013_alter_clientopinionmodel_decription_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientopinionModel',
        ),
    ]
