# Generated by Django 3.2.4 on 2021-11-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0002_auto_20211115_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messasdsage',
        ),
    ]
