# Generated by Django 3.2.4 on 2021-11-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0004_auto_20211115_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('closed', 'Closed')], default='new', max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('hizmet', models.CharField(blank=True, max_length=60, null=True)),
                ('sehir', models.CharField(blank=True, max_length=60, null=True)),
                ('ilce', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teklif isteği',
                'verbose_name_plural': 'Teklif istekleri',
                'ordering': ['name'],
            },
        ),
    ]
