# Generated by Django 3.2.4 on 2021-11-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0006_teklif_uyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklif',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, choices=[('instagram', 'İnstagram'), ('twitter', 'Twitter'), ('facebook', 'Facebook')]),
        ),
    ]
