# Generated by Django 3.2.4 on 2021-11-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0008_auto_20211115_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklif',
            name='uyer',
            field=models.CharField(blank=True, choices=[('instagram', 'İnstagram'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], default='instagram', max_length=600, null=True),
        ),
    ]
