# Generated by Django 3.2.4 on 2021-11-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0009_alter_teklif_uyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teklif',
            old_name='uyer',
            new_name='u_yer',
        ),
    ]
